export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	RESET_USER: 'RESET_USER',

	ADD_BOOKING: 'ADD_BOOKING',
	EDIT_BOOKING: 'EDIT_BOOKING',
	SET_BOOKING: 'SET_BOOKING',
	DELETE_BOOKING: 'DELETE_BOOKING',
	SET_BOOKINGS: 'SET_BOOKINGS',
	SET_RESERVED_DATES: 'SET_RESERVED_DATES',
	RESET_BOOKINGS: 'RESET_BOOKINGS',
	REQUEST_BOOKING_ERROR: 'REQUEST_BOOKING_ERROR',
	REQUEST_ROOMS_ERROR: 'REQUEST_BOOKINGS_ERROR',

	ADD_COMMENT: 'ADD_COMMENT',
	DELETE_COMMENT: 'DELETE_COMMENT',
	EDIT_COMMENT: 'EDIT_COMMENT',
	SET_COMMENTS: 'SET_COMMENTS',
	RESET_COMMENTS: 'RESET_COMMENTS',
	REQUEST_COMMENT_ERROR: 'REQUEST_COMMENT_ERROR',

	REQUEST: 'REQUEST',
	REQUEST_SUCCESS: 'REQUEST_SUCCESS',
	REQUEST_ERROR: 'REQUEST_ERROR',
	ISAUTH: 'ISAUTH',
	LOGOUT: 'LOGOUT',

	SET_SEARCH: 'SET_SEARCH',
	SET_ARRIVAL_DATE: 'SET_ARRIVAL_DATE',
	SET_COUNT_DAYS: 'SET_COUNT_DAYS',
	SET_DEPARTURE_DATE: 'SET_DEPARTURE_DATE',
	SET_GUESTS_AMOUNT: 'SET_GUESTS_AMOUNT',

	SET_ROOM: 'SET_ROOM',
	ADD_ROOM: 'ADD_ROOM',
	EDIT_ROOM: 'EDIT_ROOM',
	RESET_ROOM: 'RESET_ROOM',
	REQUEST_ROOM_ERROR: 'REQUEST_ROOM_ERROR',

	SET_ROOMS: 'SET_ROOMS',
	SET_ROOMS_LOADING: 'SET_ROOMS_LOADING',
	RESET_ROOMS: 'RESET_ROOMS',
};
